### ISSUE TITLE
Introduce support for puzzles in issues

### ISSUE THREAD

**Issue by skapral** [skapral/puzzlerbot#1]
Subj.

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#7](https://github.com/skapral/puzzlerbot/issues/7), [#8](https://github.com/skapral/puzzlerbot/issues/8) are still not solved.

**Comment by 0pdd** [comment]
@skapral the puzzle [#8](https://github.com/skapral/puzzlerbot/issues/8) is still not solved; solved: [#7](https://github.com/skapral/puzzlerbot/issues/7).

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#11](https://github.com/skapral/puzzlerbot/issues/11), [#12](https://github.com/skapral/puzzlerbot/issues/12) are still not solved; solved: [#7](https://github.com/skapral/puzzlerbot/issues/7), [#8](https://github.com/skapral/puzzlerbot/issues/8).

**Comment by 0pdd** [comment]
@skapral 4 puzzles [#11](https://github.com/skapral/puzzlerbot/issues/11), [#12](https://github.com/skapral/puzzlerbot/issues/12), [#15](https://github.com/skapral/puzzlerbot/issues/15), [#16](https://github.com/skapral/puzzlerbot/issues/16) are still not solved; solved: [#7](https://github.com/skapral/puzzlerbot/issues/7), [#8](https://github.com/skapral/puzzlerbot/issues/8).

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#12](https://github.com/skapral/puzzlerbot/issues/12), [#15](https://github.com/skapral/puzzlerbot/issues/15) are still not solved; solved: [#11](https://github.com/skapral/puzzlerbot/issues/11), [#16](https://github.com/skapral/puzzlerbot/issues/16), [#7](https://github.com/skapral/puzzlerbot/issues/7), [#8](https://github.com/skapral/puzzlerbot/issues/8).

**Comment by 0pdd** [comment]
@skapral the puzzle [#12](https://github.com/skapral/puzzlerbot/issues/12) is still not solved; solved: [#11](https://github.com/skapral/puzzlerbot/issues/11), [#15](https://github.com/skapral/puzzlerbot/issues/15), [#16](https://github.com/skapral/puzzlerbot/issues/16), [#7](https://github.com/skapral/puzzlerbot/issues/7), [#8](https://github.com/skapral/puzzlerbot/issues/8).
