### ISSUE TITLE
Introduce support for puzzles in pull requests

### ISSUE THREAD

**Issue by skapral** [skapral/puzzlerbot#2]
Subj.

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#17](https://github.com/skapral/puzzlerbot/issues/17), [#18](https://github.com/skapral/puzzlerbot/issues/18) are still not solved.

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#17](https://github.com/skapral/puzzlerbot/issues/17), [#20](https://github.com/skapral/puzzlerbot/issues/20) are still not solved; solved: [#18](https://github.com/skapral/puzzlerbot/issues/18).

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#17](https://github.com/skapral/puzzlerbot/issues/17), [#22](https://github.com/skapral/puzzlerbot/issues/22) are still not solved; solved: [#18](https://github.com/skapral/puzzlerbot/issues/18), [#20](https://github.com/skapral/puzzlerbot/issues/20).

**Comment by 0pdd** [comment]
@skapral the puzzle [#22](https://github.com/skapral/puzzlerbot/issues/22) is still not solved; solved: [#17](https://github.com/skapral/puzzlerbot/issues/17), [#18](https://github.com/skapral/puzzlerbot/issues/18), [#20](https://github.com/skapral/puzzlerbot/issues/20).
