### ISSUE TITLE
Describe how puzzlerbot parses puzzles in comments

### ISSUE THREAD

**Issue by skapral** [skapral/puzzlerbot#31]
Subj.

**Comment by 0pdd** [comment]
@skapral 2 puzzles [#33](https://github.com/skapral/puzzlerbot/issues/33), [#34](https://github.com/skapral/puzzlerbot/issues/34) are still not solved.

**Comment by 0pdd** [comment]
@skapral the puzzle [#33](https://github.com/skapral/puzzlerbot/issues/33) is still not solved; solved: [#34](https://github.com/skapral/puzzlerbot/issues/34).
