### ISSUE TITLE
Misprints in README.md

### ISSUE THREAD

**Issue by skapral** [skapral/puzzlerbot#43]
- `Puzzle Driven Development` instead of `Puzzle Driver Development`
- `Once the issue of pull request is closed,` - "of" -> "or"

**Comment by paulodamaso** [comment]
- `Code base is volatile. Puzzles in the code are rarely stay in one line.` - removed `are`
- `Some code is added, some code is removed, some codebase is changing intentionally` - "changing" -> "changed"
- `When parsing comments and seaking for puzzles, @puzzlerbot splits each comment to` - "seaking" -> "seeking"
