### ISSUE TITLE
Introduce puzzler-github module

### ISSUE THREAD

**Issue by skapral** [skapral/puzzlerbot#69]
## Description of issue/proposal

Having all classes in `puzzler-web` module is not convenient when it comes to supporting more tools (#58). `puzzler-github` must be forked from `puzzler-web`, containing all classes related to GitHub integration support.

## Steps to reproduce
N/A

## Expected result
N/A

## Actual result
N/A

## Response from web hook 
N/A

**Comment by 0pdd** [comment]
@skapral the puzzle [#72](https://github.com/skapral/puzzlerbot/issues/72) is still not solved.
